### Model
model_name_or_path: allenai/Llama-3.1-Tulu-3-8B-SFT
adapter_name_or_path: output/llama3-dpo  # <--- Loads the adapter we just trained

### Method
stage: sft
do_predict: true                      # <--- key: Predict mode
finetuning_type: lora
predict_with_generate: true

### Dataset
eval_dataset: dpo_test          # defined in dataset_info.json
template: llama3
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 4

### Output
output_dir: prediction/llama3-dpo
overwrite_output_dir: true
per_device_eval_batch_size: 16