### Model
model_name_or_path: allenai/Llama-3.1-Tulu-3-8B-SFT
# adapter_name_or_path:  <--- REMOVED! This forces it to use the base model.

### Method
stage: sft
do_predict: true
predict_with_generate: true

### Dataset
eval_dataset: dpo_test            # defined in dataset_info.json
template: llama3
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 4

### Output
output_dir: prediction/base-dpo-llama  # <--- Different output folder
overwrite_output_dir: true
per_device_eval_batch_size: 16
