### Model
model_name_or_path: google/gemma-3-4b-it
# adapter_name_or_path:  <--- REMOVED! This forces it to use the base model.

### Method
stage: sft
do_predict: true
predict_with_generate: true

### Dataset
eval_dataset: dpo_test            # defined in dataset_info.json
template: gemma
cutoff_len: 1024
max_samples: 100
overwrite_cache: true
preprocessing_num_workers: 4

### Output
output_dir: saves/gemma-zero-shot  # <--- Different output folder
overwrite_output_dir: true
per_device_eval_batch_size: 4
report_to: none